### PR TITLE
feat: Profile-saving feature

### PR DESCRIPTION
**Pull request by DedsecKnight**

### CODE REVIEW

**Comment by uy-seng** [comment]
need to to hard refresh after updating the profile to see the changes, i think it would be a much more better experience to refresh the changes itself without user having to manually reload the page to reflect the changes.

https://github.com/user-attachments/assets/2c5e5e32-23db-4fb6-8f51-522b543c76f5

**Comment by uy-seng** [comment]
How many hackathons have you attended before? -> 0 value is not being saved

https://github.com/user-attachments/assets/569d9ffc-c717-4bab-b91b-4cb69980eaaf

**Comment by uy-seng** [comment]
unable to click "Save Profile" in the following section

image

**Review by uy-seng — APPROVED** [review]
lgmt!

**Review by uy-seng — CHANGES_REQUESTED** [review]
would be nice to change the cursor when hovering over "Save Profile", cursor is not being changed smh.
edit: not sure if the cursor is clickable, but i spam clicked a few times for it to appear profile saved.

**Review by uy-seng — APPROVED** [review]

**Review by salmanjaher — CHANGES_REQUESTED** [review]
saving should be sep from submitting application (need to verify checkboxes + required fields)

**Review by salmanjaher — APPROVED** [review]
lgtm

**Pull request merged**
