### PR TITLE
Add hype video embed

### PR DESCRIPTION
**Pull request by danyobosayo**

### CODE REVIEW

**Review by salmanjaher — CHANGES_REQUESTED** [review]
Mobile view break video scaling & breaks background image

**Comment by DedsecKnight** [comment]
Still have white gap on screen with high resolution. Might wanna stretch it out a bit further. 
Shot-2024-09-18-105123

**Comment by salmanjaher** [comment]
any updates on this?

**Comment by DedsecKnight** [comment]
> any updates on this?

Merging this in now since this should work with most of the screen size. Another PR will be created to address larger screen size.

**Pull request merged**
