### PR TITLE
feat(home): Update assets

### PR DESCRIPTION
**Pull request by vvyn**

### CODE REVIEW

**Comment by DedsecKnight** [comment]
fish2
Can you make these fishes less dead?

**Comment by DedsecKnight** [comment]
Optional: Can you make these fishes swim around the text instead of under the text?
fish1

**Comment by raywa04** [comment]
> Optional: Can you make these fishes swim around the text instead of under the text? fish1

I pushed a commit that should somewhat resolve it for laptop screens, ill try to see what I can do for smaller screens in my other pr

**Review by DedsecKnight — APPROVED** [review]
:100:

**Pull request merged**
